export const TOGGLE_THEME = 'TOGGLE_MODE';
export const SET_INPUT = 'SET_INPUT';
export const FILTER_REGION = 'FILTER_REGION';
export const COUNTRY_DETAILS = 'COUNTRY_DETAILS';
export const CLOSE_DETAILS = 'CLOSE_DETAILS';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const SEARCH_TERM = 'SEARCH_TERM';
export const SEARCH_RESULT = 'SEARCH_RESULT';
